import React, { useState } from 'react';
import { HardDrive, DownloadCloud, UploadCloud, Clock, ShieldCheck, DatabaseBackup } from 'lucide-react';

export default function BackupPage() {
  const [loading, setLoading] = useState(false);
  const [lastBackup, setLastBackup] = useState('11 April 2026, 18:30 PM');

  const handleExportBackup = () => {
    setLoading(true);
    setTimeout(() => {
       setLoading(false);
       setLastBackup(new Date().toLocaleString());
       alert("✓ Backup successful! Saved to: D:\\VaahanBooks_Backups\\VB_Backup_" + new Date().toISOString().split('T')[0] + ".vbak");
    }, 2000);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 animate-fade-in p-6">
      
      <div className="flex justify-between items-center bg-surface-900 border border-surface-800 p-6 rounded-2xl shadow-xl backdrop-blur-sm">
        <div className="flex items-center gap-4">
           <div className="p-3 bg-purple-500/10 rounded-xl border border-purple-500/20">
             <DatabaseBackup className="text-purple-400" />
           </div>
           <div>
             <h1 className="text-3xl font-bold font-display text-white">Backup & Restore</h1>
             <p className="text-surface-400 mt-1 text-sm">Secure your Financial Data Offline</p>
           </div>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-6">
        
        {/* Local Backup Panel */}
        <div className="bg-surface-900 border border-surface-800 p-6 rounded-2xl shadow-lg ring-1 ring-white/5 space-y-6">
           <div>
              <h2 className="text-lg font-bold text-white flex items-center gap-2">
                <DownloadCloud className="text-brand-400" size={20}/> Take Offline Backup
              </h2>
              <p className="text-surface-400 text-sm mt-1">
                Creates an encrypted `.vbak` file containing your SQLite Database (Financials + GST + Inventory). Safe to store on a Pen Drive.
              </p>
           </div>

           <div className="bg-surface-950 border border-surface-800 p-4 rounded-xl flex items-center justify-between">
              <div className="flex items-center gap-3">
                 <Clock className="text-surface-500" size={18} />
                 <div>
                    <div className="text-xs text-surface-500">Last Local Backup Taken</div>
                    <div className="text-sm text-white font-bold">{lastBackup}</div>
                 </div>
              </div>
              <div className="bg-green-500/10 text-green-400 text-xs px-2 py-1 rounded font-bold border border-green-500/20">
                 Secure
              </div>
           </div>

           <button 
             onClick={handleExportBackup}
             disabled={loading}
             className="w-full flex justify-center items-center gap-2 bg-gradient-to-r from-purple-600 to-purple-500 hover:from-purple-500 hover:to-purple-400 text-white px-6 py-4 rounded-xl shadow-lg font-bold transition-all disabled:opacity-50"
           >
             {loading ? <span className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></span> : <HardDrive size={18} />}
             {loading ? 'Generating Encrypted Backup...' : 'Export DB to Pen Drive / Local Folder'}
           </button>
        </div>

        {/* Restore Panel */}
        <div className="bg-surface-900 border border-surface-800 p-6 rounded-2xl shadow-lg ring-1 ring-white/5 space-y-6 h-full border-t-4 border-t-red-500">
           <div>
              <h2 className="text-lg font-bold text-white flex items-center gap-2">
                <UploadCloud className="text-red-400" size={20}/> Restore from Backup
              </h2>
              <p className="text-surface-400 text-sm mt-1">
                <span className="text-red-400 font-bold">WARNING:</span> Restoring a `.vbak` file will overwrite ALL your current local data. Use only in case of system failure.
              </p>
           </div>

           <div className="bg-red-500/10 border border-red-500/20 p-4 rounded-xl flex items-start gap-3 mt-4">
              <ShieldCheck className="text-red-400 shrink-0" size={20} />
              <div className="text-red-300 text-sm">
                 Only encrypted backups generated by VaahanBooks can be restored. You will need your Master Password to decrypt.
              </div>
           </div>

           <button className="w-full flex justify-center items-center gap-2 bg-surface-950 hover:bg-red-500/20 border border-red-500/50 text-red-400 px-6 py-4 rounded-xl transition-colors font-bold mt-auto">
             <UploadCloud size={18} /> Select .vbak File to Restore
           </button>
        </div>

      </div>
    </div>
  );
}
