name: Build and Release Electron App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Native Deps (IMPORTANT)
        run: npx electron-builder install-app-deps

      - name: Build App
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build
